name: Release Upload Asset
description: Upload files to a GitHub release
inputs:
  release-id:
    description: The ID of the release to which to upload files.
    required: false
  files:
    description: Paths to the files to upload. Separated by newline. You can specify the MIME type for each file after the file path, preceded by a `&`.
    required: true
runs:
  using: docker
  image: Dockerfile
  env:
    GH_INPUTS: ${{ toJSON(inputs) }}

branding:
  icon: upload
  color: blue
