name: Release Upload Asset
description: Upload files to a GitHub release
inputs:
  gh-token:
    description: The GitHub token to use for authentication.
    required: true
  release-id:
    description: The ID of the release to which to upload files.
    required: false
  files:
    description: Paths to the files to upload. Separated by newline.
    required: true
runs:
  using: docker
  image: docker://ghcr.io/cloudnode-pro/release-upload-asset:1.0.5
  env:
    GH_INPUTS: ${{ toJSON(inputs) }}

branding:
  icon: upload
  color: blue
